'use client';

import React, { useState } from 'react';
import { LegalCase } from '../lib/types';

interface DLSAInfoCardProps {
  currentCase: LegalCase;
}

export const DLSAInfoCard: React.FC<DLSAInfoCardProps> = ({ currentCase }) => {
  const [selectedState, setSelectedState] = useState('Delhi');
  const [copiedSummary, setCopiedSummary] = useState(false);

  const stateLimits: Record<string, string> = {
    Delhi: '₹3,00,000 per annum (Delhi SLSA)',
    Maharashtra: '₹3,00,000 per annum (MSLSA)',
    Karnataka: '₹3,00,000 per annum (KSLSA)',
    Haryana: '₹3,00,000 per annum (HALSA)',
    'Uttar Pradesh': '₹3,00,000 per annum (UPSLSA)',
    'West Bengal': '₹3,00,000 per annum (WBSLSA)',
    'Tamil Nadu': '₹3,00,000 per annum (TNSLSA)'
  };

  const handleExportDossierForDLSA = () => {
    const summary = `
LEGAL AID DOSSIER FOR DLSA PANEL ADVOCATE
===================================================
Case Docket ID: ${currentCase.id}
Subject: ${currentCase.title}
Legal Category: ${currentCase.category}
Jurisdiction: ${currentCase.jurisdiction}
Current Status: ${currentCase.status}

1. CITIZEN STATEMENT OF GRIEVANCE:
${currentCase.citizenStatement}

2. MATERIAL FACTS IN DOCKET:
${currentCase.keyFacts.map((f, i) => `  [${i + 1}] (${f.category}) ${f.statement} [Confidence: ${f.confidence}]`).join('\n')}

3. ATTACHED EVIDENCE LIST:
${currentCase.evidenceList.map((e, i) => `  [${i + 1}] ${e.name} (${e.category}) - Status: ${e.statusLabel}`).join('\n')}

4. RELEVANT STATUTORY PROVISIONS IDENTIFIED:
${currentCase.legalSources.map((s, i) => `  [${i + 1}] ${s.title} (${s.section}) - ${s.relevance}`).join('\n')}

5. ESTIMATED CLAIM / RELIEF SOUGHT:
${currentCase.claimAmount || 'Restitution & Statutory Redressal'}

Generated by Legal Saathi Civic Legal Assistant for presentation to District Legal Services Authority (DLSA).
    `.trim();

    navigator.clipboard.writeText(summary);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2500);
  };

  return (
    <div className="w-full space-y-6">
      {/* Top Banner: What is DLSA */}
      <div className="bg-surface-container-lowest dark:bg-[#0F131C] rounded-2xl p-6 shadow-sm border border-outline-variant/30 flex flex-col gap-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-emerald-600 text-white flex items-center justify-center shrink-0 shadow-sm">
              <span className="material-symbols-outlined text-2xl">balance</span>
            </div>
            <div>
              <span className="text-[10px] font-bold text-emerald-800 dark:text-emerald-300 uppercase tracking-wider font-mono bg-emerald-100 dark:bg-emerald-950 px-2 py-0.5 rounded">
                LEGAL SERVICES AUTHORITIES ACT, 1987
              </span>
              <h3 className="font-heading text-xl font-extrabold text-on-surface mt-0.5">
                District Legal Services Authority (DLSA) Guidance
              </h3>
            </div>
          </div>

          <a
            href="tel:15100"
            className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold transition-colors flex items-center gap-2 self-start sm:self-auto shadow-sm"
          >
            <span className="material-symbols-outlined text-base">phone_in_talk</span>
            <span>Call NALSA 15100 (Toll-Free 24/7)</span>
          </a>
        </div>

        <p className="text-xs text-on-surface-variant leading-relaxed">
          The <strong>District Legal Services Authority (DLSA)</strong> operates in every district court complex
          across India under Article 39A of the Constitution of India and the Legal Services Authorities Act, 1987.
          It ensures that no citizen is denied justice on account of economic, social, or geographical disability.
        </p>

        {/* 3 Core Legal Aid Pillars */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 pt-2">
          <div className="bg-surface-container-low dark:bg-[#161F30] p-4 rounded-xl border border-outline-variant/30 text-xs">
            <div className="flex items-center gap-2 text-primary dark:text-primary-fixed font-bold mb-1">
              <span className="material-symbols-outlined text-base">person</span>
              <span>Free Panel Advocate</span>
            </div>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              Appointment of experienced panel lawyers to represent you in civil, tenancy, labor, and tribunal courts without advocate fees.
            </p>
          </div>

          <div className="bg-surface-container-low dark:bg-[#161F30] p-4 rounded-xl border border-outline-variant/30 text-xs">
            <div className="flex items-center gap-2 text-primary dark:text-primary-fixed font-bold mb-1">
              <span className="material-symbols-outlined text-base">receipt_long</span>
              <span>Court & Process Fees Borne</span>
            </div>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              Payment of court fees, drafting charges, stamp papers, typing, and certified copy expenses by the Authority.
            </p>
          </div>

          <div className="bg-surface-container-low dark:bg-[#161F30] p-4 rounded-xl border border-outline-variant/30 text-xs">
            <div className="flex items-center gap-2 text-primary dark:text-primary-fixed font-bold mb-1">
              <span className="material-symbols-outlined text-base">handshake</span>
              <span>Lok Adalat & Mediation</span>
            </div>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              Fast-track pre-litigation settlement through Lok Adalat or court-annexed mediation with binding legal force.
            </p>
          </div>
        </div>
      </div>

      {/* Statutory Eligibility Section (Neutral & Accurate) */}
      <div className="bg-surface-container-lowest dark:bg-[#0F131C] rounded-2xl p-6 shadow-sm border border-outline-variant/30 space-y-4">
        <h4 className="font-heading text-base font-bold text-on-surface flex items-center gap-2">
          <span className="material-symbols-outlined text-secondary">verified_user</span>
          Statutory Eligibility under Section 12 of the Legal Services Authorities Act, 1987
        </h4>

        <div className="bg-amber-50 dark:bg-amber-950/40 border-l-4 border-amber-500 rounded-xl p-3 text-xs text-amber-900 dark:text-amber-300 leading-relaxed">
          <strong>LEGAL AID NOTICE:</strong> Eligibility depends on applicable rules, category, and individual circumstances.
          Legal Saathi provides statutory information but does not determine final eligibility; the decision rests solely
          with the Member Secretary of the respective District or State Legal Services Authority.
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="bg-surface-container-low dark:bg-[#161F30] p-4 rounded-xl space-y-2">
            <span className="font-bold text-on-surface block text-[11px] uppercase tracking-wider">
              Categorical Entitlement (Irrespective of Income):
            </span>
            <ul className="space-y-1.5 pl-4 list-disc text-on-surface-variant text-[11px]">
              <li>Women and children</li>
              <li>Members of Scheduled Castes (SC) or Scheduled Tribes (ST)</li>
              <li>Persons with disability (under Rights of Persons with Disabilities Act, 2016)</li>
              <li>Industrial workmen affected by labor disputes or mass retrenchment</li>
              <li>Victims of trafficking, disaster, ethnic violence, or custody</li>
            </ul>
          </div>

          <div className="bg-surface-container-low dark:bg-[#161F30] p-4 rounded-xl space-y-2">
            <div className="flex items-center justify-between">
              <span className="font-bold text-on-surface text-[11px] uppercase tracking-wider">
                Income Ceilings by State:
              </span>
              <select
                value={selectedState}
                onChange={(e) => setSelectedState(e.target.value)}
                className="text-xs p-1 rounded bg-surface-container-lowest dark:bg-[#0F131C] border border-outline-variant/40 font-semibold text-on-surface"
              >
                {Object.keys(stateLimits).map((st) => (
                  <option key={st} value={st}>{st}</option>
                ))}
              </select>
            </div>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              Citizens not falling under categorical entitlement qualify if annual household income does not exceed the ceiling set by the State Government:
            </p>
            <div className="p-2.5 rounded-lg bg-surface-container-lowest dark:bg-[#0F131C] border border-outline-variant/30 text-xs font-mono font-bold text-emerald-800 dark:text-emerald-300">
              {selectedState}: {stateLimits[selectedState]}
            </div>
          </div>
        </div>
      </div>

      {/* How to Proceed & Prepare Dossier */}
      <div className="bg-surface-container-lowest dark:bg-[#0F131C] rounded-2xl p-6 shadow-sm border border-outline-variant/30 space-y-4">
        <h4 className="font-heading text-base font-bold text-on-surface flex items-center gap-2">
          <span className="material-symbols-outlined text-primary">description</span>
          How to Apply & Present Your Case to DLSA
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <div className="p-3.5 rounded-xl bg-surface-container-low dark:bg-[#161F30] flex flex-col gap-1">
            <span className="font-mono font-bold text-secondary text-sm">01</span>
            <span className="font-bold text-on-surface">Locate Court Front Office</span>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              Visit the Front Office of DLSA situated inside your district court complex (e.g., Saket District Court for South Delhi).
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-surface-container-low dark:bg-[#161F30] flex flex-col gap-1">
            <span className="font-mono font-bold text-secondary text-sm">02</span>
            <span className="font-bold text-on-surface">Submit Legal Aid Form</span>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              Fill the simple 1-page form available free of charge at the front desk along with an Aadhaar copy and income affidavit.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-surface-container-low dark:bg-[#161F30] flex flex-col gap-1">
            <span className="font-mono font-bold text-secondary text-sm">03</span>
            <span className="font-bold text-on-surface">Meet Panel Advocate</span>
            <p className="text-on-surface-variant text-[11px] leading-relaxed">
              A designated legal aid advocate will review your case dossier, formulate petition drafts, and represent you in court.
            </p>
          </div>
        </div>

        {/* Export Case Dossier for DLSA */}
        <div className="pt-2 flex flex-col sm:flex-row items-center justify-between gap-3 bg-surface-container-low dark:bg-[#161F30]/60 p-4 rounded-xl border border-outline-variant/30">
          <div>
            <span className="font-bold text-on-surface text-xs block">
              Prepare Case Docket for DLSA Advocate
            </span>
            <p className="text-[11px] text-on-surface-variant">
              Copy a structured brief of Case #{currentCase.id} including facts, evidence list, and statutory citations to hand over to the legal aid counsel.
            </p>
          </div>

          <button
            onClick={handleExportDossierForDLSA}
            className="px-4 py-2 rounded-lg bg-primary hover:bg-secondary text-white text-xs font-bold transition-colors flex items-center gap-1.5 shrink-0 shadow-sm"
            type="button"
          >
            <span className="material-symbols-outlined text-sm">content_copy</span>
            <span>{copiedSummary ? 'Dossier Copied!' : 'Copy Dossier for DLSA'}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
