-- ==============================================================================
-- 20260927000004_storage_buckets.sql
-- Legal Saathi — Supabase Storage Configuration (Phase 18)
-- Configures private storage buckets and access policies for:
--   1. evidence-files (Citizen evidence uploads: Audio, Documents, Images)
--   2. generated-drafts (Legal notices, RTIs, and complaints generated by Legal Saathi)
-- ==============================================================================

-- 1. Create Private Buckets in storage.buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
    (
        'evidence-files',
        'evidence-files',
        false,
        26214400, -- 25MB Max
        ARRAY[
            'application/pdf',
            'image/jpeg',
            'image/png',
            'image/webp',
            'audio/wav',
            'audio/mpeg',
            'audio/mp3',
            'audio/webm',
            'audio/m4a',
            'audio/ogg',
            'audio/flac'
        ]::text[]
    ),
    (
        'generated-drafts',
        'generated-drafts',
        false,
        10485760, -- 10MB Max
        ARRAY[
            'application/pdf',
            'text/plain',
            'application/json',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        ]::text[]
    )
ON CONFLICT (id) DO UPDATE SET
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Note: storage.objects RLS is managed by Supabase internally.
-- We do not ALTER TABLE storage.objects here — that requires supabase_storage_admin role.
-- Storage bucket policies below are applied directly and work via Supabase RLS.

-- 3. Storage Policies for 'evidence-files'
-- Policy: Users can only upload into their own folder: <uid>/<filename>
CREATE POLICY "Users can upload their own evidence"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'evidence-files' 
    AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Policy: Users can only read their own evidence
CREATE POLICY "Users can read their own evidence"
ON storage.objects FOR SELECT
TO authenticated
USING (
    bucket_id = 'evidence-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Policy: Users can delete their own evidence
CREATE POLICY "Users can delete their own evidence"
ON storage.objects FOR DELETE
TO authenticated
USING (
    bucket_id = 'evidence-files'
    AND (storage.foldername(name))[1] = auth.uid()::text
);

-- 4. Storage Policies for 'generated-drafts'
-- Policy: Users can read their own generated drafts
CREATE POLICY "Users can read their own drafts"
ON storage.objects FOR SELECT
TO authenticated
USING (
    bucket_id = 'generated-drafts'
    AND (storage.foldername(name))[1] = auth.uid()::text
);

-- Policy: Users can create/upload drafts into their own folder
CREATE POLICY "Users can upload their own drafts"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'generated-drafts'
    AND (storage.foldername(name))[1] = auth.uid()::text
);
